In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv('redo_merged_dataset.csv')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2970 entries, 0 to 2969
Data columns (total 61 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     2970 non-null   int64
 1   is_weekend                             2970 non-null   bool
 2   day_in_study                           2970 non-null   int64
 3   phase                                  2970 non-null   object
 4   lh                                     2970 non-null   float64
 5   estrogen                               2970 non-null   float64
 6   flow_volume                            2578 non-null   object
 7   flow_color                             2578 non-null   object
 8   appetite                               2970 non-null   object
 9   exerciselevel                          2970 non-null   object
 10  headaches                              2970 non-null   object
 11  cramps                                 2970 non-null   object
 12  sorebreasts                            2970 non-null   object
 13  fatigue                                2970 non-null   object
 14  sleepissue                             2970 non-null   object
 15  moodswing                              2970 non-null   object
 16  stress                                 2970 non-null   object
 17  foodcravings                           2970 non-null   object
 18  indigestion                            2970 non-null   object
 19  bloating                               2970 non-null   object
 20  calories_daily                         2970 non-null   float64
 21  steps_daily                            2970 non-null   float64
 22  bpm_mean                               2970 non-null   float64
 23  bpm_min                                2970 non-null   float64
 24  bpm_max                                2970 non-null   float64
 25  bpm_std                                2970 non-null   float64
 26  temp_diff_from_baseline_mean           2970 non-null   float64
 27  temp_diff_from_baseline_min            2970 non-null   float64
 28  temp_diff_from_baseline_max            2970 non-null   float64
 29  temp_diff_from_baseline_std            2970 non-null   float64
 30  glucose_mean                           2970 non-null   float64
 31  glucose_min                            2970 non-null   float64
 32  glucose_max                            2970 non-null   float64
 33  glucose_std                            2970 non-null   float64
 34  overall_score                          2970 non-null   float64
 35  composition_score                      2970 non-null   float64
 36  revitalization_score                   2970 non-null   float64
 37  duration_score                         2970 non-null   float64
 38  nightly_temperature                    2970 non-null   float64
 39  duration                               2970 non-null   float64
 40  minutestofallasleep                    2970 non-null   float64
 41  minutesasleep                          2970 non-null   float64
 42  minutesawake                           2970 non-null   float64
 43  minutesafterwakeup                     2970 non-null   float64
 44  timeinbed                              2970 non-null   float64
 45  efficiency                             2970 non-null   float64
 46  duration_exercise                      2970 non-null   float64
 47  calories_exercise                      2970 non-null   float64
 48  heartrate_exercise                     2970 non-null   float64
 49  activity_type                          2970 non-null   object
 50  in_default_zone_3                      2970 non-null   float64
 51  in_default_zone_2                      2970 non-null   float64
 52  in_default_zone_1                      2970 non-null   float64
 53  below_default_zone_1                   2970 non-null   float64
 54  birth_year                             2970 non-null   int64
 55  gender                                 2970 non-null   object
 56  ethnicity                              2970 non-null   object
 57  education                              2970 non-null   object
 58  sexually_active                        2970 non-null   object
 59  self_report_menstrual_health_literacy  2970 non-null   object
 60  age_of_first_menarche                  2970 non-null   int64
dtypes: bool(1), float64(35), int64(4), object(21)
memory usage: 1.4+ MB

In [11]:
df.columns

Index(['id', 'is_weekend', 'day_in_study', 'phase', 'lh', 'estrogen',
       'flow_volume', 'flow_color', 'appetite', 'exerciselevel', 'headaches',
       'cramps', 'sorebreasts', 'fatigue', 'sleepissue', 'moodswing', 'stress',
       'foodcravings', 'indigestion', 'bloating', 'calories_daily',
       'steps_daily', 'bpm_mean', 'bpm_min', 'bpm_max', 'bpm_std',
       'temp_diff_from_baseline_mean', 'temp_diff_from_baseline_min',
       'temp_diff_from_baseline_max', 'temp_diff_from_baseline_std',
       'glucose_mean', 'glucose_min', 'glucose_max', 'glucose_std',
       'overall_score', 'composition_score', 'revitalization_score',
       'duration_score', 'nightly_temperature', 'duration',
       'minutestofallasleep', 'minutesasleep', 'minutesawake',
       'minutesafterwakeup', 'timeinbed', 'efficiency', 'duration_exercise',
       'calories_exercise', 'heartrate_exercise', 'activity_type',
       'in_default_zone_3', 'in_default_zone_2', 'in_default_zone_1',
       'below_default_zone_1', 'birth_year', 'gender', 'ethnicity',
       'education', 'sexually_active', 'self_report_menstrual_health_literacy',
       'age_of_first_menarche'],
      dtype='object')

In [12]:
import pandas as pd

df = df.sort_values(["id", "day_in_study"]).reset_index(drop=True)

def assign_cycle(sub):
    sub = sub.copy().reset_index(drop=True)
 
    is_new_cycle = (sub["phase"] == "Menstrual") & (sub["phase"].shift(1) != "Menstrual")
   
    sub["cycle"] = is_new_cycle.cumsum()
    
    return sub

df = df.groupby("id", group_keys=False).apply(assign_cycle)

df = df[df["cycle"] > 0]

/var/tmp/ipykernel_4534/634064563.py:14: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby("id", group_keys=False).apply(assign_cycle)

In [13]:
df["cycle_length"] = (
    df.groupby(["id", "cycle"])["day_in_study"]
            .transform("count")
)

In [14]:
df.head()

,id,is_weekend,day_in_study,phase,lh,estrogen,flow_volume,flow_color,appetite,exerciselevel,...,below_default_zone_1,birth_year,gender,ethnicity,education,sexually_active,self_report_menstrual_health_literacy,age_of_first_menarche,cycle,cycle_length
19,2,False,20,Menstrual,1.0,65.7,Not at all,Not at all,Low,Low,...,1355.0,1995,Woman,East Asian,"Bachelor's degree (e.g. BA, BS)",Yes,High,13,1,31
20,2,True,21,Menstrual,4.8,81.6,Moderate,Bright Red,High,Very High,...,831.0,1995,Woman,East Asian,"Bachelor's degree (e.g. BA, BS)",Yes,High,13,1,31
21,2,True,22,Menstrual,5.8,90.2,Somewhat Light,Dark Brown / Dark Red,Moderate,Low,...,1358.0,1995,Woman,East Asian,"Bachelor's degree (e.g. BA, BS)",Yes,High,13,1,31
22,2,False,23,Menstrual,4.5,60.0,Light,Dark Brown / Dark Red,Low,Low,...,1430.0,1995,Woman,East Asian,"Bachelor's degree (e.g. BA, BS)",Yes,High,13,1,31
23,2,False,24,Follicular,3.5,60.0,Spotting / Very Light,Dark Brown / Dark Red,Moderate,Low,...,1408.0,1995,Woman,East Asian,"Bachelor's degree (e.g. BA, BS)",Yes,High,13,1,31

In [45]:
df['flow_volume'].value_counts()

flow_volume
Not at all               1969
Spotting / Very Light     175
Moderate                  119
Light                     114
Somewhat Light             80
Somewhat Heavy             54
Heavy                      47
Very Heavy                 20
Name: count, dtype: int64

In [46]:
mapping_flow_volume = {
    "Not at all": 0.0,
    "Spotting / Very Light": 1.0,
    "Light": 1.0,
    "Somewhat Light": 1.0,
    "Moderate": 2.0,
    "Somewhat Heavy": 2.0,
    "Heavy": 3.0,
    "Very Heavy": 3.0
}

df["flow_volume_score"] = df["flow_volume"].map(mapping_flow_volume)

In [47]:
#df['flow_color'].value_counts()

In [48]:
df['appetite'].value_counts()

appetite
Moderate      1443
Low            708
High           544
Very Low       181
Very High       89
Not at all       5
Name: count, dtype: int64

In [49]:
mapping = {
    "Not at all": 0.0,
    "Very Low": 1.0,
    "Low": 1.0,
    "Moderate": 2.0,
    "High": 3.0,
    "Very High": 3.0
}

df["appetite_score"] = df["appetite"].map(mapping_appetite)

In [50]:
df['exerciselevel'].value_counts()

exerciselevel
Low           1004
Moderate       873
Very Low       722
High           308
Very High       55
Not at all       8
Name: count, dtype: int64

In [51]:
df["exerciselevel_score"] = df["exerciselevel"].map(mapping)

In [52]:
df['headaches'].value_counts()

headaches
Not at all         933
Very Low/Little    866
Low                440
Moderate           403
High               233
Very High           95
Name: count, dtype: int64

In [53]:
mapping = {
    "Not at all": 0.0,
    "Very Low/Little": 1.0,
    "Low": 1.0,
    "Moderate": 2.0,
    "High": 3.0,
    "Very High": 3.0
}

In [54]:
df["headaches_score"] = df["headaches"].map(mapping)

In [55]:
df['cramps'].value_counts()

cramps
Not at all         1404
Very Low/Little     916
Moderate            232
Low                 231
High                125
Very High            62
Name: count, dtype: int64

In [56]:
df["cramps_score"] = df["cramps"].map(mapping)

In [57]:
df['sorebreasts'].value_counts()

sorebreasts
Not at all         1523
Very Low/Little     899
Low                 255
Moderate            207
High                 57
Very High            29
Name: count, dtype: int64

In [58]:
df["sorebreasts_score"] = df["sorebreasts"].map(mapping)

In [59]:
df['fatigue'].value_counts()

fatigue
Moderate           780
High               619
Low                537
Very Low/Little    445
Not at all         330
Very High          259
Name: count, dtype: int64

In [60]:
df["fatigue_score"] = df["fatigue"].map(mapping)

In [61]:
df['sleepissue'].value_counts()

sleepissue
Low                655
Very Low/Little    603
Moderate           585
Not at all         555
High               357
Very High          215
Name: count, dtype: int64

In [62]:
df["sleepissue_score"] = df["sleepissue"].map(mapping)

In [63]:
df['moodswing'].value_counts()

moodswing
Not at all         896
Very Low/Little    736
Moderate           503
Low                471
High               274
Very High           90
Name: count, dtype: int64

In [64]:
df["moodswing_score"] = df["moodswing"].map(mapping)

In [65]:
df['stress'].value_counts()

stress
Moderate           979
Low                536
High               527
Very Low/Little    328
Not at all         320
Very High          280
Name: count, dtype: int64

In [66]:
df["stress_score"] = df["stress"].map(mapping)

In [67]:
df['foodcravings'].value_counts()

foodcravings
Not at all         735
Very Low/Little    580
Low                568
Moderate           534
High               387
Very High          166
Name: count, dtype: int64

In [68]:
df["foodcravings_score"] = df["foodcravings"].map(mapping)

In [69]:
df['indigestion'].value_counts()

indigestion
Not at all         1005
Very Low/Little     695
Low                 494
Moderate            470
High                219
Very High            87
Name: count, dtype: int64

In [70]:
df["indigestion_score"] = df["indigestion"].map(mapping)

In [71]:
df['bloating'].value_counts()

bloating
Not at all         901
Very Low/Little    611
Low                540
Moderate           508
High               316
Very High           94
Name: count, dtype: int64

In [72]:
df["bloating_score"] = df["bloating"].map(mapping)

In [73]:
df.head()

,id,is_weekend,day_in_study,phase,lh,estrogen,flow_volume,flow_color,appetite,exerciselevel,...,headaches_score,cramps_score,sorebreasts_score,fatigue_score,sleepissue_score,moodswing_score,stress_score,foodcravings_score,indigestion_score,bloating_score
0,2,True,1,Fertility,2.9,78.5,Not at all,Not at all,Moderate,Very Low,...,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0
1,2,False,2,Fertility,3.2,126.9,Not at all,Not at all,Moderate,Very Low,...,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,1.0,0.0
2,2,False,3,Fertility,5.7,187.5,Not at all,Not at all,Low,Very Low,...,0.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,0.0
3,2,False,4,Fertility,26.4,220.3,Not at all,Not at all,Moderate,Moderate,...,0.0,0.0,0.0,3.0,2.0,2.0,3.0,0.0,0.0,0.0
4,2,False,5,Fertility,19.5,287.7,Not at all,Not at all,Moderate,Low,...,0.0,0.0,0.0,3.0,3.0,2.0,3.0,0.0,0.0,0.0

In [74]:
df_cleaned = df.copy()

In [77]:
df_cleaned.columns

Index(['id', 'is_weekend', 'day_in_study', 'phase', 'lh', 'estrogen',
       'flow_volume', 'flow_color', 'appetite', 'exerciselevel', 'headaches',
       'cramps', 'sorebreasts', 'fatigue', 'sleepissue', 'moodswing', 'stress',
       'foodcravings', 'indigestion', 'bloating', 'calories_daily',
       'steps_daily', 'bpm_mean', 'bpm_min', 'bpm_max', 'bpm_std',
       'temp_diff_from_baseline_mean', 'temp_diff_from_baseline_min',
       'temp_diff_from_baseline_max', 'temp_diff_from_baseline_std',
       'glucose_mean', 'glucose_min', 'glucose_max', 'glucose_std',
       'overall_score', 'composition_score', 'revitalization_score',
       'duration_score', 'nightly_temperature', 'duration',
       'minutestofallasleep', 'minutesasleep', 'minutesawake',
       'minutesafterwakeup', 'timeinbed', 'efficiency', 'duration_exercise',
       'calories_exercise', 'heartrate_exercise', 'activity_type',
       'in_default_zone_3', 'in_default_zone_2', 'in_default_zone_1',
       'below_default_zone_1', 'birth_year', 'gender', 'ethnicity',
       'education', 'sexually_active', 'self_report_menstrual_health_literacy',
       'age_of_first_menarche', 'flow_volume_score', 'appetite_score',
       'exerciselevel_score', 'headaches_score', 'cramps_score',
       'sorebreasts_score', 'fatigue_score', 'sleepissue_score',
       'moodswing_score', 'stress_score', 'foodcravings_score',
       'indigestion_score', 'bloating_score'],
      dtype='object')

In [78]:
df_cleaned.drop(columns = ['flow_volume', 'appetite', 'exerciselevel', 'headaches',
       'cramps', 'sorebreasts', 'fatigue', 'sleepissue', 'moodswing', 'stress',
       'foodcravings', 'indigestion', 'bloating'], inplace = True)

In [81]:
dict_path = '/home/jupyter/Feature Selection/df.csv'
df.to_csv(dict_path, index=False)
print(f"\n✓ Data dictionary saved to: {dict_path}")
print(f"\nPreview:")
print(df.head(10).to_string(index=False))

✓ Data dictionary saved to: /home/jupyter/Feature Selection/df.csv

Preview:
 id  is_weekend  day_in_study     phase   lh  estrogen flow_volume flow_color appetite exerciselevel       headaches          cramps     sorebreasts  fatigue      sleepissue       moodswing    stress foodcravings indigestion        bloating  calories_daily  steps_daily  bpm_mean  bpm_min  bpm_max   bpm_std  temp_diff_from_baseline_mean  temp_diff_from_baseline_min  temp_diff_from_baseline_max  temp_diff_from_baseline_std  glucose_mean  glucose_min  glucose_max  glucose_std  overall_score  composition_score  revitalization_score  duration_score  nightly_temperature   duration  minutestofallasleep  minutesasleep  minutesawake  minutesafterwakeup  timeinbed  efficiency  duration_exercise  calories_exercise  heartrate_exercise activity_type  in_default_zone_3  in_default_zone_2  in_default_zone_1  below_default_zone_1  birth_year gender  ethnicity                       education sexually_active self_report_menstrual_health_literacy  age_of_first_menarche  flow_volume_score  appetite_score  exerciselevel_score  headaches_score  cramps_score  sorebreasts_score  fatigue_score  sleepissue_score  moodswing_score  stress_score  foodcravings_score  indigestion_score  bloating_score
  2        True             1 Fertility  2.9      78.5  Not at all Not at all Moderate      Very Low Very Low/Little Very Low/Little Very Low/Little      Low Very Low/Little Very Low/Little  Moderate          Low         Low Very Low/Little          1568.0       1366.0 61.907280     45.0     99.0  8.668029                     -2.108785                    -5.844396                     1.305604                     1.917520      8.603623          6.9         11.4     1.012867           87.0               21.0                  22.0            44.0            34.014396 29820000.0                  0.0          444.0          53.0                 0.0      497.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                0.0                2.0                1438.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              1.0           1.0                1.0            1.0               1.0              1.0           2.0                 1.0                1.0             1.0
  2       False             2 Fertility  3.2     126.9  Not at all Not at all Moderate      Very Low      Not at all      Not at all      Not at all Moderate      Not at all      Not at all  Moderate   Not at all         Low      Not at all          1558.0       1584.0 63.661694     45.0    106.0  9.501314                     -1.895660                    -5.449442                     1.815558                     1.876533      7.045818          5.4          9.7     1.067610           90.0               22.0                  21.0            47.0            34.329517 29760000.0                  0.0          459.0          37.0                 0.0      496.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                0.0                2.0                1438.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            2.0               0.0              0.0           2.0                 0.0                1.0             0.0
  2       False             3 Fertility  5.7     187.5  Not at all Not at all      Low      Very Low      Not at all      Not at all      Not at all      Low             Low      Not at all      High   Not at all         Low      Not at all          1579.0       1189.0 65.289199     49.0    123.0 11.478889                     -2.083015                    -7.494487                     1.850513                     2.322759      6.662868          5.6         10.3     1.014935           89.0               20.0                  22.0            47.0            34.703078 31320000.0                  0.0          481.0          41.0                 0.0      522.0        98.0                0.0                0.0                 0.0   No Exercise                0.0                0.0               37.0                1333.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             1.0                  1.0              0.0           0.0                0.0            1.0               1.0              0.0           3.0                 0.0                1.0             0.0
  2       False             4 Fertility 26.4     220.3  Not at all Not at all Moderate      Moderate      Not at all      Not at all      Not at all     High        Moderate        Moderate      High   Not at all  Not at all      Not at all          1958.0       6654.0 70.607410     49.0    131.0 15.223260                     -2.847116                    -6.869442                     1.590558                     1.894750      7.102198          5.5         12.0     1.548503           80.0               21.0                  19.0            40.0            33.197196 28380000.0                  0.0          443.0          30.0                 0.0      473.0        99.5                0.0                0.0                 0.0   No Exercise                0.0                0.0              150.0                1289.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  2.0              0.0           0.0                0.0            3.0               2.0              2.0           3.0                 0.0                0.0             0.0
  2       False             5 Fertility 19.5     287.7  Not at all Not at all Moderate           Low      Not at all      Not at all      Not at all     High            High        Moderate      High   Not at all  Not at all      Not at all          1804.0       4760.0 77.011422     52.0    128.0 14.435853                     -2.778274                    -8.984487                     2.090513                     2.768820      7.215636          5.5         12.9     1.662909           71.0               19.0                  11.0            41.0            34.609702 30240000.0                  0.0          444.0          60.0                 8.0      504.0        97.0                0.0                0.0                 0.0   No Exercise                0.0                0.0               87.0                1353.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            3.0               3.0              2.0           3.0                 0.0                0.0             0.0
  2       False             6 Fertility  4.6     117.3  Not at all Not at all      Low           Low      Not at all      Not at all      Not at all Moderate        Moderate        Moderate Very High   Not at all  Not at all      Not at all          1673.0       3818.0 66.265932     48.0    136.0 12.335209                     -2.199834                    -8.619275                     1.755725                     2.128160      7.280524          6.0         10.9     1.039481           87.0               19.0                  21.0            47.0            34.074064 33000000.0                  5.0          504.0          46.0                 0.0      550.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                2.0               29.0                1409.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             1.0                  1.0              0.0           0.0                0.0            2.0               2.0              2.0           3.0                 0.0                0.0             0.0
  2        True             7    Luteal  4.4      99.8  Not at all Not at all Moderate          High      Not at all      Not at all      Not at all Moderate        Moderate      Not at all       Low     Moderate  Not at all      Not at all          2622.0      24424.0 78.292592     49.0    144.0 16.532830                     -2.495531                    -9.099487                     1.845513                     2.723349      7.043956          5.8          9.9     0.900516           70.0               18.0                  18.0            34.0            35.164059 25560000.0                  0.0          376.0          50.0                 0.0      426.0        95.5                0.0                0.0                 0.0   No Exercise                0.0                3.0              253.0                1184.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  3.0              0.0           0.0                0.0            2.0               2.0              0.0           1.0                 2.0                0.0             0.0
  2        True             8    Luteal  8.1     241.2  Not at all Not at all Moderate           Low      Not at all      Not at all      Not at all     High             Low      Not at all       Low     Moderate  Not at all      Not at all          2133.0      12451.0 70.867775     48.0    117.0 13.067864                     -2.134840                    -9.217002                     1.967998                     2.370995      7.107115          5.2         10.5     1.294781           81.0               20.0                  16.0            45.0            34.504223 32040000.0                  0.0          462.0          72.0                 1.0      534.0        98.0                0.0                0.0                 0.0   No Exercise                0.0                0.0              119.0                1320.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            3.0               1.0              0.0           1.0                 2.0                0.0             0.0
  2       False             9    Luteal  4.8     159.9  Not at all Not at all     High           Low      Not at all      Not at all      Not at all Moderate        Moderate      Not at all  Moderate   Not at all  Not at all      Not at all          1583.0       2105.0 67.394224     51.0    126.0 10.271922                     -0.849223                    -6.404517                     1.775483                     1.461259      7.248496          5.9         10.5     0.888213           88.0               22.0                  19.0            47.0            34.839745 32880000.0                  0.0          514.0          34.0                 0.0      548.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                0.0               24.0                1356.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             3.0                  1.0              0.0           0.0                0.0            2.0               2.0              0.0           2.0                 0.0                0.0             0.0
  2       False            10    Luteal  4.8     177.6  Not at all Not at all Moderate           Low      Not at all      Not at all      Not at all     High        Moderate      Not at all  Moderate     Moderate  Not at all        Moderate          1906.0       7891.0 70.971245     52.0    147.0 14.036546                     -1.567818                    -6.656870                     1.728130                     2.065801      7.282331          5.8         10.5     1.005395           82.0               20.0                  20.0            42.0            34.914354 28800000.0                  0.0          434.0          46.0                 0.0      480.0        99.0                0.0                0.0                 0.0   No Exercise                0.0               11.0               68.0                1361.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            3.0               2.0              0.0           2.0                 2.0                0.0             2.0

In [80]:
dict_path = '/home/jupyter/Feature Selection/df_cleaned.csv'
df_cleaned.to_csv(dict_path, index=False)
print(f"\n✓ Data dictionary saved to: {dict_path}")
print(f"\nPreview:")
print(df_cleaned.head(10).to_string(index=False))

✓ Data dictionary saved to: /home/jupyter/Feature Selection/df_cleaned.csv

Preview:
 id  is_weekend  day_in_study     phase   lh  estrogen flow_color  calories_daily  steps_daily  bpm_mean  bpm_min  bpm_max   bpm_std  temp_diff_from_baseline_mean  temp_diff_from_baseline_min  temp_diff_from_baseline_max  temp_diff_from_baseline_std  glucose_mean  glucose_min  glucose_max  glucose_std  overall_score  composition_score  revitalization_score  duration_score  nightly_temperature   duration  minutestofallasleep  minutesasleep  minutesawake  minutesafterwakeup  timeinbed  efficiency  duration_exercise  calories_exercise  heartrate_exercise activity_type  in_default_zone_3  in_default_zone_2  in_default_zone_1  below_default_zone_1  birth_year gender  ethnicity                       education sexually_active self_report_menstrual_health_literacy  age_of_first_menarche  flow_volume_score  appetite_score  exerciselevel_score  headaches_score  cramps_score  sorebreasts_score  fatigue_score  sleepissue_score  moodswing_score  stress_score  foodcravings_score  indigestion_score  bloating_score
  2        True             1 Fertility  2.9      78.5 Not at all          1568.0       1366.0 61.907280     45.0     99.0  8.668029                     -2.108785                    -5.844396                     1.305604                     1.917520      8.603623          6.9         11.4     1.012867           87.0               21.0                  22.0            44.0            34.014396 29820000.0                  0.0          444.0          53.0                 0.0      497.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                0.0                2.0                1438.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              1.0           1.0                1.0            1.0               1.0              1.0           2.0                 1.0                1.0             1.0
  2       False             2 Fertility  3.2     126.9 Not at all          1558.0       1584.0 63.661694     45.0    106.0  9.501314                     -1.895660                    -5.449442                     1.815558                     1.876533      7.045818          5.4          9.7     1.067610           90.0               22.0                  21.0            47.0            34.329517 29760000.0                  0.0          459.0          37.0                 0.0      496.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                0.0                2.0                1438.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            2.0               0.0              0.0           2.0                 0.0                1.0             0.0
  2       False             3 Fertility  5.7     187.5 Not at all          1579.0       1189.0 65.289199     49.0    123.0 11.478889                     -2.083015                    -7.494487                     1.850513                     2.322759      6.662868          5.6         10.3     1.014935           89.0               20.0                  22.0            47.0            34.703078 31320000.0                  0.0          481.0          41.0                 0.0      522.0        98.0                0.0                0.0                 0.0   No Exercise                0.0                0.0               37.0                1333.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             1.0                  1.0              0.0           0.0                0.0            1.0               1.0              0.0           3.0                 0.0                1.0             0.0
  2       False             4 Fertility 26.4     220.3 Not at all          1958.0       6654.0 70.607410     49.0    131.0 15.223260                     -2.847116                    -6.869442                     1.590558                     1.894750      7.102198          5.5         12.0     1.548503           80.0               21.0                  19.0            40.0            33.197196 28380000.0                  0.0          443.0          30.0                 0.0      473.0        99.5                0.0                0.0                 0.0   No Exercise                0.0                0.0              150.0                1289.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  2.0              0.0           0.0                0.0            3.0               2.0              2.0           3.0                 0.0                0.0             0.0
  2       False             5 Fertility 19.5     287.7 Not at all          1804.0       4760.0 77.011422     52.0    128.0 14.435853                     -2.778274                    -8.984487                     2.090513                     2.768820      7.215636          5.5         12.9     1.662909           71.0               19.0                  11.0            41.0            34.609702 30240000.0                  0.0          444.0          60.0                 8.0      504.0        97.0                0.0                0.0                 0.0   No Exercise                0.0                0.0               87.0                1353.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            3.0               3.0              2.0           3.0                 0.0                0.0             0.0
  2       False             6 Fertility  4.6     117.3 Not at all          1673.0       3818.0 66.265932     48.0    136.0 12.335209                     -2.199834                    -8.619275                     1.755725                     2.128160      7.280524          6.0         10.9     1.039481           87.0               19.0                  21.0            47.0            34.074064 33000000.0                  5.0          504.0          46.0                 0.0      550.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                2.0               29.0                1409.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             1.0                  1.0              0.0           0.0                0.0            2.0               2.0              2.0           3.0                 0.0                0.0             0.0
  2        True             7    Luteal  4.4      99.8 Not at all          2622.0      24424.0 78.292592     49.0    144.0 16.532830                     -2.495531                    -9.099487                     1.845513                     2.723349      7.043956          5.8          9.9     0.900516           70.0               18.0                  18.0            34.0            35.164059 25560000.0                  0.0          376.0          50.0                 0.0      426.0        95.5                0.0                0.0                 0.0   No Exercise                0.0                3.0              253.0                1184.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  3.0              0.0           0.0                0.0            2.0               2.0              0.0           1.0                 2.0                0.0             0.0
  2        True             8    Luteal  8.1     241.2 Not at all          2133.0      12451.0 70.867775     48.0    117.0 13.067864                     -2.134840                    -9.217002                     1.967998                     2.370995      7.107115          5.2         10.5     1.294781           81.0               20.0                  16.0            45.0            34.504223 32040000.0                  0.0          462.0          72.0                 1.0      534.0        98.0                0.0                0.0                 0.0   No Exercise                0.0                0.0              119.0                1320.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            3.0               1.0              0.0           1.0                 2.0                0.0             0.0
  2       False             9    Luteal  4.8     159.9 Not at all          1583.0       2105.0 67.394224     51.0    126.0 10.271922                     -0.849223                    -6.404517                     1.775483                     1.461259      7.248496          5.9         10.5     0.888213           88.0               22.0                  19.0            47.0            34.839745 32880000.0                  0.0          514.0          34.0                 0.0      548.0        99.0                0.0                0.0                 0.0   No Exercise                0.0                0.0               24.0                1356.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             3.0                  1.0              0.0           0.0                0.0            2.0               2.0              0.0           2.0                 0.0                0.0             0.0
  2       False            10    Luteal  4.8     177.6 Not at all          1906.0       7891.0 70.971245     52.0    147.0 14.036546                     -1.567818                    -6.656870                     1.728130                     2.065801      7.282331          5.8         10.5     1.005395           82.0               20.0                  20.0            42.0            34.914354 28800000.0                  0.0          434.0          46.0                 0.0      480.0        99.0                0.0                0.0                 0.0   No Exercise                0.0               11.0               68.0                1361.0        1995  Woman East Asian Bachelor's degree (e.g. BA, BS)             Yes                                  High                     13                0.0             2.0                  1.0              0.0           0.0                0.0            3.0               2.0              0.0           2.0                 2.0                0.0             2.0